// import { Toaster } from "@/components/ui/sonner"
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// import Script from "next/script";
import "./globals.css";
// import { PersistGate } from "redux-persist/integration/react";
import localFont from "next/font/local";
import Providers from "./providers";
// import Head from "next/head";
// import { SessionProvider } from "next-auth/react";
import ClientLayout from "./customerSessionProvider";
const ibmPlexSans = localFont({
  src: [
    { path: "/fonts/IBMPlexSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "/fonts/IBMPlexSans-Medium.ttf", weight: "500", style: "normal" },
    { path: "/fonts/IBMPlexSans-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "/fonts/IBMPlexSans-Bold.ttf", weight: "700", style: "normal" },
  ],
});

const bebasNeue = localFont({
  src: [
    { path: "/fonts/BebasNeue-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: "--bebas-neue",
});
export const metadata = {
  title: "Ice Queen By Ice",
  description: "Generated by create next app",
};

// import { Provider } from "react-redux";
// import { store, persistor } from "@/store/store";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <title>Ice Queen By Ice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
      </Head> */}
      <body
        className={`${ibmPlexSans.className} ${bebasNeue.variable} antialiased`}
      >
        {" "}
        <ClientLayout>
          <Providers>
            {/* <Script
              src="https://js.paystack.co/v1/inline.js"
              strategy="beforeInteractive"
            /> */}
            {children}
          </Providers>
        </ClientLayout>
      </body>
    </html>
  );
}
